name: size_type
description: Size data type for Dart.
version: 0.0.1
#homepage: https://github.com/minerhub/dart-size-type

environment:
  sdk: '>=2.0.0 <3.0.0'
  meta: ^1.1.6

dev_dependencies:
  test: ^1.3.2